### ISSUE TITLE
more visible gridlines

### ISSUE THREAD

**Issue by SRCarpen** [hdugan/NTLviewer#1]
This is a wonderful tool for scouting patterns to guide future analysis. 
Can gridlines be more visible, perhaps a darker or contrasting color?

**Comment by hdugan** [comment]
@SRCarpen I darkened the lines a bit, but not too much that it overwhelms the data. Let me know your thoughts:
https://data-viz.it.wisc.edu/connect/#/apps/246/access

**Comment by SRCarpen** [comment]
Hi Hilary,

Yes this helps. Thanks for making the fix.

This viewer is a great idea. Exploring the data is fast and easy, versus the old days when I had to download a bunch of .csv files and plot them.

Thanks!  ~ Steve
