### ISSUE TITLE
Can you add a sentence about citing the data. It may be better to direct people to EDI rather than the NTL website and adding the exact location of the datasets.

### ISSUE THREAD

**Issue by cgries** [hdugan/NTLviewer#2]

**Comment by hdugan** [comment]
@cgries check out the update! https://data-viz.it.wisc.edu/connect/#/apps/246/access
It should link to whichever dataset is being shown. Let me know your thoughts.

**Comment by cgries** [comment]
I like the link. But it seems to insert the data landing page into the Rstudio server and then there is no way to get back to your visualization. Wouldn't it be better to open that link in a new window to not lose the application?

**Comment by hdugan** [comment]
👍  I think I got it to open in a new tab. Can you double check for me?

**Comment by cgries** [comment]
yes, you did. I was just going to send you a screenshot and then it worked correctly! Great!

**Comment by hdugan** [comment]
Awesome, going to close this comment, but let me know any other ideas/updates 😄
